Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split("""
luatos.c
""")
CPPPATH = [cwd]

group = DefineGroup('luatos_port', src, depend = ['PKG_USING_LUATOS_SOC'], CPPPATH = CPPPATH)

Return('group')
