Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Split("""
luatos.c
""")
CPPPATH = [cwd]

group = DefineGroup('port', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
